# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f98581f5c63822842f06644755e40a10beae0c716e2b5b8669261082a57693881442cbebf875eb2320261aa442765bab78780b056cdb28d3eec8994a71864c

test:
  secret_key_base: 2728bafe048cbfc89e45465035e2bed668cc1261c796459dee11be0b3d3589bfc584142a947e3e72635ec710ca9ac6f166cb629cbfec5467e237d8cb9bddcc23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
